module.exports = {
  moduleFileExtensions: ['js'],
  transformIgnorePatterns: [
    // transform es6 modules generated by rescript
    "/node_modules/(?!@glennsl/bs-jest|bs-platform|@rescript|@tomvardasca|bs-jest-dom|bs-dom-testing-library).+\\.js$"
  ],
  collectCoverageFrom: [
    "src/**/*"
  ]
};
