module.exports = {
  moduleFileExtensions: ['js'],
  transformIgnorePatterns: [
    // transform es6 modules generated by rescript
    "/node_modules/(?!@glennsl/bs-jest|bs-platform|@rescript).+\\.js$"
  ],
};
