// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import Button from "@material-ui/core/Button";
import Typography from "@material-ui/core/Typography";
import * as GoogleIcon$DictyComponentsLogin from "./icons/GoogleIcon.bs.js";

import { makeStyles } from "@material-ui/core/styles"
const useButtonStyles = makeStyles((theme) => ({
  button: {
    padding: theme.spacing(1.5, 3, 1.5, 3),
    textTransform: "none",
    backgroundColor: "#cfd8dc",
    "&:hover": {
      backgroundColor: "#cfd8dc"
    }
  },
  subtitle: {
    width: "100%"
  }
}))
;

var Button$1 = {};

var Typography$1 = {};

function GoogleButton(Props) {
  var text = Props.text;
  var handleClick = Props.handleClick;
  return React.createElement(Button, {
              variant: "contained",
              size: "large",
              fullWidth: true,
              startIcon: React.createElement(GoogleIcon$DictyComponentsLogin.make, {}),
              onClick: handleClick,
              children: React.createElement(Typography, {
                    variant: "h6",
                    align: "center",
                    color: "textSecondary",
                    children: text
                  })
            });
}

var make = GoogleButton;

var $$default = GoogleButton;

export {
  Button$1 as Button,
  Typography$1 as Typography,
  make ,
  $$default ,
  $$default as default,
  
}
/*  Not a pure module */
