// Generated by ReScript, PLEASE EDIT WITH CARE

import React, { Fragment } from "react"
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome"
import { library } from "@fortawesome/fontawesome-svg-core"
import {
  faGoogle,
  faFacebookF,
  faLinkedinIn,
  faTwitter,
  faYoutube,
  faInstagram,
  faGithubAlt,
  faDropbox,
} from "@fortawesome/free-brands-svg-icons"
import {
  IconContainer,
  socialButtonColors,
  StyledButton,
} from "./loginStyles.bs"

library.add(
  faGoogle,
  faFacebookF,
  faLinkedinIn,
  faTwitter,
  faYoutube,
  faInstagram,
  faGithubAlt,
  faDropbox,
)

// convert names to desired fontawesome icon name
const name2Icon = {
  google: "google",
  facebook: "facebook-f",
  linkedin: "linkedin-in",
  twitter: "twitter",
  youtube: "youtube",
  instagram: "instagram",
  github: "github-alt",
  dropbox: "dropbox",
}

/**
 * This is the main login component that generates the user-specified social buttons.
 */
const Login = ({ buttons, onClick }: Props) => (
  <Fragment>
    {buttons.map((name, i) => (
      <StyledButton
        style={{ backgroundColor: socialButtonColors[name] }}
        onClick={() => {
          onClick(name)
        }}
        key={i}>
        <IconContainer>
          {name === "orcid" ? (
            <i className="ai ai-orcid" />
          ) : (
            <FontAwesomeIcon icon={["fab", name2Icon[name]]} />
          )}
        </IconContainer>
        &nbsp; Sign in with {name}
      </StyledButton>
    ))}
  </Fragment>
)

export default Login

export {}
/*  Not a pure module */
