// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "@rescript/std/lib/es6/curry.js";
import * as React from "react";
import * as ReactDOMStyle from "@rescript/react/src/ReactDOMStyle.bs.js";
import * as Core from "@material-ui/core";
import * as Styles from "@material-ui/core/styles";
import * as OrcidIcon$DictyComponentsLogin from "./icons/OrcidIcon.bs.js";

var useStyles = Styles.makeStyles(function (theme) {
      return {
              subtitle: {
                color: "#4D4D4D",
                fontWeight: "600",
                width: "100%"
              },
              button: ReactDOMStyle.unsafeAddProp({
                    backgroundColor: "#a6ce39",
                    paddingTop: String(Curry._1(theme.spacing, 2)) + "px",
                    paddingRight: String(Curry._1(theme.spacing, 3)) + "px",
                    paddingBottom: String(Curry._1(theme.spacing, 2)) + "px",
                    paddingLeft: String(Curry._1(theme.spacing, 3)) + "px",
                    textTransform: "none"
                  }, "&:hover", {
                    backgroundColor: "#739d00"
                  })
            };
    });

var Styles$1 = {
  useStyles: useStyles
};

function OrcidButton(Props) {
  var text = Props.text;
  var handleClick = Props.handleClick;
  var classes = Curry._1(useStyles, undefined);
  return React.createElement(Core.Button, {
              onClick: handleClick,
              children: React.createElement(Core.Typography, {
                    align: "center",
                    children: text,
                    className: classes.subtitle,
                    color: "textSecondary",
                    variant: "inherit"
                  }),
              className: classes.button,
              fullWidth: true,
              size: "large",
              startIcon: React.createElement(OrcidIcon$DictyComponentsLogin.make, {}),
              variant: "contained"
            });
}

var make = OrcidButton;

var $$default = OrcidButton;

export {
  Styles$1 as Styles,
  make ,
  $$default ,
  $$default as default,
  
}
/* useStyles Not a pure module */
