name: Testing (Pull Requests)
on:
  pull_request:
    types: [edited, labeled, opened, synchronize, reopened]
jobs:
  test:
    name: Unit tests
    runs-on: ubuntu-20.04
    steps:
      - name: set up node.js
        uses: actions/setup-node@v3.2.0
        with:
          node-version: 14.17.0
      - name: check out code
        uses: actions/checkout@v3
      - name: install
        run: yarn
      - name: generate build and bundle
        run: yarn bundle
      - name: unit tests
        run: yarn test --coverage
        env:
          CI: true
      - name: upload test coverage to codecov
        uses: codecov/codecov-action@v3.1.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
